//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentSingup
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string FatherName { get; set; }
        [Required]
        public string MotherName { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public int Age { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string @class { get; set; }
        [Required]
        public string GoingTo { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public Nullable<long> ContactNo { get; set; }
        [Required]
        public string Tution { get; set; }
        [Required]
        public string Tutor { get; set; }
       
        public string UserImg { get; set; }
        
        public HttpPostedFileBase Img_file { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Compare("Password")]
       
        public string CoPassword { get; set; }
    }
}
