//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tutorregi
    {
        public int Id { get; set; }
        [Required]
        public string Fullname { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string maritalsts { get; set; }
        [Required]
        public string country { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        [Required]
        public string qualification { get; set; }
        [Required]
        [DisplayName("Subject")]
        public string degree { get; set; }
        [Required]
        public string experience { get; set; }
        [Required]
        public Nullable<long> contactNo_ { get; set; }
        [Required]
        public string password { get; set; }
        
        public string Image { get; set; }
        public HttpPostedFileBase Img_File { get; set; }
       

      
        
    }
}
